src/objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>DocumentTypeId__c</fullName>
        <label>Document Type ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
</CustomObject>

All Onboard/objects/Document__mdt.object
<CustomObject>
    <description>Stores details of required/optional documents for an application</description>
    <fields>
        <fullName>Accepted_File_Format__c</fullName>
        <defaultValue>&quot;.pdf,.png,.jpg&quot;</defaultValue>
        <description>Comma-separated list of file extensions that can be uploaded in the format .ext, such as .pdf, .jpg, or .png</description>
        <inlineHelpText>Comma-separated list of file extensions that can be uploaded in the format .ext, such as .pdf, .jpg, or .png</inlineHelpText>
        <label>Accepted File Format</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <referenceTo>Document_Category__mdt</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents_del</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Document_Name__c</fullName>
        <label>Document Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_Link__c</fullName>
        <description>The URL of the template file.</description>
        <inlineHelpText>The URL of the template for the specific flow document type.</inlineHelpText>
        <label>File Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Icon__c</fullName>
        <description>The URL of the icon. The icon is displayed in the left hand side of the flow document name.</description>
        <inlineHelpText>The URL of the icon. The icon is displayed in the left hand side of the flow document name.</inlineHelpText>
        <label>Icon</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Mandatory__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if this document is required to pass the document check.</description>
        <inlineHelpText>Indicates if this document is required to pass the document check.</inlineHelpText>
        <label>Is Mandatory?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <description>Points/Score for the flow document.</description>
        <inlineHelpText>Points/Score for the flow document.</inlineHelpText>
        <label>Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Flow Document</label>
    <pluralLabel>Flow Documents</pluralLabel>
</CustomObject>

src/objects/Document_Category__mdt.object
<CustomObject>
    <description>Stores the category name for a group of Flow Documents</description>
    <label>Flow Document Category</label>
    <pluralLabel>Flow Document Categories</pluralLabel>
</CustomObject>

src/classes/DocumentUploadController.cls
/*
 * Copyright (c) 2020, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */
 
public with sharing class DocumentUploadController {


    @AuraEnabled
    public static List<DocumentWrapper> getAllDocuments(String recordId) {
        List<DocumentWrapper> documents = new List<DocumentWrapper>();
        Map<String, List<ContentVersion>> groupedDocuments = groupDocumentsByType(recordId);
        List<Document__mdt> documentTypes = [
                SELECT Id, Category__r.MasterLabel, Document_Name__c, Score__c, Description__c, Icon__c,
                        Accepted_File_Format__c, File_Link__c, Mandatory__c
                FROM Document__mdt
                WHERE Active__c = true
                WITH SECURITY_ENFORCED
                ORDER BY Mandatory__c DESC, Score__c DESC
        ];
        for (Document__mdt docType : documentTypes) {
            DocumentWrapper wrapper = new DocumentWrapper();
            wrapper.document = docType;
            if (groupedDocuments.containsKey(docType.Id)) {
                wrapper.uploadedDocuments.addAll(groupedDocuments.get(docType.Id));
                documents.add(wrapper);
            }
        }
        System.Debug(documents);
        return documents;
    }

    @AuraEnabled
    public static List<DocumentWrapper> getDocuments(String recordId, String category) {
        List<DocumentWrapper> documents = new List<DocumentWrapper>();
        Map<String, List<ContentVersion>> groupedDocuments = groupDocumentsByType(recordId);

        List<Document__mdt> documentTypes = [
                SELECT Id, Category__r.MasterLabel, Document_Name__c, Score__c, Description__c, Icon__c,
                        Accepted_File_Format__c, File_Link__c, Mandatory__c
                FROM Document__mdt
                WHERE Category__r.MasterLabel = :category AND Active__c = true
                WITH SECURITY_ENFORCED
                ORDER BY Mandatory__c DESC, Score__c DESC
        ];
        for (Document__mdt docType : documentTypes) {
            DocumentWrapper wrapper = new DocumentWrapper();
            wrapper.document = docType;
            if (groupedDocuments.containsKey(docType.Id)) {
                wrapper.uploadedDocuments.addAll(groupedDocuments.get(docType.Id));
            }
            documents.add(wrapper);
        }
        return documents;
    }

    @AuraEnabled
    public static void updateDocuments(String documentTypeId, List<String> documentIds) {
        List<ContentVersion> uploadedDocuments = [
                SELECT Id, DocumentTypeId__c
                FROM ContentVersion
                WHERE ContentDocumentId IN :documentIds
                WITH SECURITY_ENFORCED
        ];
        for (ContentVersion doc : uploadedDocuments) {
            doc.DocumentTypeId__c = documentTypeId;
        }
        update uploadedDocuments;
    }

    @AuraEnabled
    public static void deleteDocument(String documentId) {
        if (String.isNotBlank(documentId)) {
            List<ContentDocument> documents = [SELECT Id FROM ContentDocument WHERE Id = :documentId];
            delete documents;
        }
    }

    private static List<String> retrieveRelatedDocumentIds(String recordId) {
        List<ContentDocumentLink> documentLinks = [
                SELECT ContentDocumentId
                FROM ContentDocumentLink
                WHERE LinkedEntityId = :recordId
                WITH SECURITY_ENFORCED
        ];
        List<String> documentIds = new List<String>();
        for (ContentDocumentLink documentLink : documentLinks) {
            documentIds.add(documentLink.ContentDocumentId);
        }
        return documentIds;
    }

    private static Map<String, List<ContentVersion>> groupDocumentsByType(String recordId) {
        Map<String, List<ContentVersion>> groupedDocuments = new Map<String, List<ContentVersion>>();

        if (String.isNotBlank(recordId)) {
            List<ContentVersion> uploadedDocuments = [
                    SELECT Id, ContentDocumentId, Title, Description,
                            FileType, FileExtension, DocumentTypeId__c, LastModifiedDate
                    FROM ContentVersion
                    WHERE ContentDocumentId IN :retrieveRelatedDocumentIds(recordId) AND DocumentTypeId__c != NULL
                    WITH SECURITY_ENFORCED
            ];
            for (ContentVersion cv : uploadedDocuments) {
                String documentTypeId = cv.DocumentTypeId__c;
                if (!groupedDocuments.containsKey(documentTypeId)) {
                    groupedDocuments.put(documentTypeId, new List<ContentVersion>());
                }
                groupedDocuments.get(documentTypeId).add(cv);
            }
        }
        return groupedDocuments;
    }

    public class DocumentWrapper {
        @AuraEnabled
        public Document__mdt document;

        @AuraEnabled
        public List<ContentVersion> uploadedDocuments;

        public DocumentWrapper() {
            uploadedDocuments = new List<ContentVersion>();
        }
    }

    public static Boolean getCustomLabels() {
        String promptMessage = Label.Cmp_PromptMessage;
        String promptTitle = Label.Cmp_PromptTitle;
        String promptNegativeButtonText = Label.Cmp_PromptNegativeButtonText;
        String promptPositiveButtonText = Label.Cmp_PromptPositiveButtonText;
        return true;
    }

}