src/objects/Flow_Session__c.object
<CustomObject>
    <description>Stores the custom data input during the Flow Interview and can be used to distribute data to other objects as needed</description>
    <fields>
        <fullName>Two_Factor_Authentication_Code__c</fullName>
        <description>Used to store the temporary randomly generated Two Factor Authentication Code for when it is requested</description>
        <inlineHelpText>Temporary Storage of the Two Factor Authentication Code. The code is generated when requested.</inlineHelpText>
        <label>Two Factor Authentication Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Two_Factor_Authentication_Expiry__c</fullName>
        <label>Two Factor Authentication Expiry</label>
        <type>DateTime</type>
    </fields>
    <label>Flow Session</label>
    <nameField>
        <displayFormat>Flow Session-{00000}</displayFormat>
        <label>Flow Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flow Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

All Onboard/classes/AllOnboard_CodeGeneratorTest.cls
/*
 * Copyright (c) 2020, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */
 
@isTest(SeeAllData=true)
global with sharing class AllOnboard_CodeGeneratorTest {
    @isTest
    global static void given_aCodeIsRequested_when_aCodeIsGenerated_then_theCodeIsStoredAgainstTheSessionRecord() {
        List<AllOnboard_CodeGenerator.CodeGeneratorInput> inputs = new List<AllOnboard_CodeGenerator.CodeGeneratorInput>();
        AllOnboard_CodeGenerator.CodeGeneratorInput input = new AllOnboard_CodeGenerator.CodeGeneratorInput();
        Flow_Session__c flowSession = new Flow_Session__c();

        input.sObjectName = 'Flow_Session__c';
        input.fieldName = 'Two_Factor_Authentication_Code__c';
        input.expiryFieldName = 'Two_Factor_Authentication_Expiry__c';
        input.codeLength = 6;
        input.expiryDuration = 60;
        input.recordId = [
                SELECT Id
                FROM Flow_Session__c
                ORDER BY CreatedDate DESC
                LIMIT 1
        ].Id;
        input.isAlphanumeric = true;

        input.expiryDuration = 0;
        inputs.add(input);

        AllOnboard_CodeGenerator.generateCode(inputs);

        flowSession = [
                SELECT Two_Factor_Authentication_Code__c
                FROM Flow_Session__c
                WHERE Id = :input.recordId
        ];

        System.assertNotEquals(flowSession.Two_Factor_Authentication_Code__c, null);
    }

    @isTest
    global static void given_aCodeIsRequested_when_theInputsAreInvalid_then_aDMLExceptionIsThrown() {
        List<AllOnboard_CodeGenerator.CodeGeneratorInput> inputs = new List<AllOnboard_CodeGenerator.CodeGeneratorInput>();
        AllOnboard_CodeGenerator.CodeGeneratorInput input = new AllOnboard_CodeGenerator.CodeGeneratorInput();
        List<Flow_Session__c> flowSessions = new List<Flow_Session__c>();

        input.sObjectName = 'XXX_Flow_Session__c';
        input.fieldName = 'Two_Factor_Authentication_Code__c';
        input.expiryFieldName = 'Two_Factor_Authentication_Expiry__c';
        input.codeLength = 6;
        input.expiryDuration = 60;
        input.recordId = [
                SELECT Id
                FROM User
                ORDER BY CreatedDate DESC
                LIMIT 1
        ].Id;

        input.expiryDuration = 0;
        inputs.add(input);

        AllOnboard_CodeGenerator.generateCode(inputs);

        flowSessions = [
                SELECT Two_Factor_Authentication_Code__c
                FROM Flow_Session__c
                WHERE Id = :input.recordId
        ];

        System.assertEquals(flowSessions.size(), 0);
    }

    @isTest
    global static void given_aCodeIsRequested_when_theExpiryDurationIsNotSupplied_then_anExpiryDurationIsDefaulted() {
        List<AllOnboard_CodeGenerator.CodeGeneratorInput> inputs = new List<AllOnboard_CodeGenerator.CodeGeneratorInput>();
        AllOnboard_CodeGenerator.CodeGeneratorInput input = new AllOnboard_CodeGenerator.CodeGeneratorInput();
        Flow_Session__c flowSession = new Flow_Session__c();

        input.sObjectName = 'Flow_Session__c';
        input.fieldName = 'Two_Factor_Authentication_Code__c';
        input.expiryFieldName = 'Two_Factor_Authentication_Expiry__c';
        input.codeLength = 6;
        input.recordId = [
                SELECT Id
                FROM Flow_Session__c
                ORDER BY CreatedDate DESC
                LIMIT 1
        ].Id;

        input.expiryDuration = null;
        inputs.add(input);

        AllOnboard_CodeGenerator.generateCode(inputs);

        flowSession = [
                SELECT Two_Factor_Authentication_Code__c,
                        Two_Factor_Authentication_Expiry__c
                FROM Flow_Session__c
                WHERE Id = :input.recordId
        ];

        // Test the default expiration time is at least 29 minutes
        System.assert(((flowSession.Two_Factor_Authentication_Expiry__c.getTime() - Datetime.now().getTime()) / 60000) >= 29);
    }
}